s3_bucket = "terraform-state-aipril-class-aia"
s3_folder_project = "terraform_ec2"
s3_folder_region = "us-east-1"
s3_folder_type = "class"
s3_tfstate_file = "infrastructure.tfstate"

environment = "dev"
region      = "us-east-1"
public_key  = "ssh-rsa "
ami_id      = "ami-02eac2c0129f6376b"
